### ISSUE TITLE
Can't seem to get it to work.

### ISSUE THREAD

**Issue by sdeese** [packagecontrol/requests#2]
I get the following when I try to save the plugin with import reqeusts
:
reloading plugin User.qb
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 76, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/stephendeese/Library/Application Support/Sublime Text 3/Packages/User/qb.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

I created the .json file and put it in the every dir that deals with packages (non of them worked).

When I run Satisfy Dependencies, I get:
 Package Control: All dependencies have been satisfied

Any ideas?

**Comment by FichteFoll** [comment]
Please provide the full console log after you ran "Satisfy Dependencies" and the `dependencies.json` file in your package.
