### ISSUE TITLE
Package is imported form another path / Package are not isolated

### ISSUE THREAD

**Issue by mfuentesg** [packagecontrol/requests#3]
i am solving a issue of a plugin, and i am getting the follow error.

```
Traceback (most recent call last):

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Packages/SyncSettings/sync_settings/libs/gist_api.py", line 23, in __init__
    response = requests.get(self.BASE_URL + '/user?access_token=' + token)

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Installed Packages/sublime-github.sublime-package/lib/requests/api.py", line 55, in get
    return request('get', url, **kwargs)

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Installed Packages/sublime-github.sublime-package/lib/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Installed Packages/sublime-github.sublime-package/lib/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Installed Packages/sublime-github.sublime-package/lib/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)

  File "/Users/marcelo/Library/Application Support/Sublime Text 3/Installed Packages/sublime-github.sublime-package/lib/requests/adapters.py", line 331, in send
    raise SSLError(e)

requests.exceptions.SSLError: [Errno 20] Not a directory
```
My plugin send a requests using the `requests` package but the trace error indicates that the `requests` package is imported from another path and not from package control dependency path.

how i can solve this issue?

**Comment by FichteFoll** [comment]
Enter this in ST's console and report the result: `import requests; requests.__file__`

**Comment by mfuentesg** [comment]
```python
import requests; requests.__file__
```

```
Sublime Text 3 v3083
.../Installed Packages/sublime-github.sublime-package/lib/requests/__init__.py
```

**Comment by FichteFoll** [comment]
Well, that's your package to complain about then. It's messing with sys.path by adding its custom library path *in front of any other path*, which effectively breaks requests for everyone as it requires to be unpackaged unless patched, afaics.
